### PR TITLE
add merge_netsim_scenarios

### PR DESCRIPTION
**Pull request by AdrienLeGuillou**
functions to merge netsim scenarios into single netsim files similar to `merge.netsim` or into currated `data.frame`.

`merge_netsim_scenarios` takes the same parameters as `merge.netsim` but sets `param.error` to `FALSE` by default and turns `keep.other` to `FALSE` internally if the `other` element is not present.

`merge_nestsim_scenario_tibble` converts the scenarios into `tibble` and keep only the last `steps_to_keep` rows. Additionally, a `cols` argument can be used to limit the columns to save. This could be useful for plots that requires many steps but few columns. The `cols` argument is a `<tidy-select>`, meaning that it accept the same syntax as `dplyr::select`.

examples:

```r
merge_netsim_scenarios("data/intermediate/scenarios", "test_merged")
```

will read the sim files from `"data/intermediate/scenarios"` and store the resulting merge files into `"test_merged"`.

```r
merge_netsim_scenarios_tibble(
  "data/intermediate/scenarios",
  "test_tibble",
  52,
  cols = dplyr::matches("^doxy")
)
```

will read the sim files from `"data/intermediate/scenarios"` and store the resulting `tibbles`  into `"test_tibble"`. Theses `tibbles` contain only the last 52 steps and all the columns which name starts with `"doxy"`. (the columns `batch_number`, `sim` and `time` are always kept as well.

To use this with a workflow, add the following step

```r
wf <- add_workflow_step(
  wf_summary = wf,
  step_tmpl = step_tmpl_do_call(
    what = EpiModelHPC::merge_netsim_scenarios_tibble,
    args = list(
      sim_dir = "data/intermediate/scenarios",
      output_dir = "test_sc",
      steps_to_keep = 52 * 10,
      cols = rlang::quo(dplyr::matches("^doxy")) # rlang::quo required for lazy eval
    ),
    setup_lines = hpc_configs$r_loader
  ),
  sbatch_opts = list(
    "mail-type" = "END",
    "cpus-per-task" = 1,
    "time" = "02:00:00",
    "mem" = "15G"
  )
)
```

### CODE REVIEW

**Comment by AdrienLeGuillou** [comment]
next steps to finalize:

- [ ] parallelize internally
- [ ] make bespoke step_tmpl to remove the need for `rlang::quo`
- [ ] real documentation / vignette

@smjenness this is very much a WIP so do not hesitate if you have ideas / opinions

@clchand23 @laurammann  you can try these features by installing `EpiModel/EpiModelHPC@merges`

**Comment by AdrienLeGuillou** [comment]
both merge functions and swf steps are added and functional.
I made a quick new "workflow file" on the Template repo (https://github.com/EpiModel/EpiModelHIV-Template/pull/17).
I will have to re-order some files and update the vignette. But I think it's good to go for now. (I have multiple things that I will have to update at once in the template and it's doc)

**Comment by smjenness** [comment]
@AdrienLeGuillou : please address these R CMD Check warnings: https://github.com/EpiModel/EpiModelHPC/actions/runs/5179109886/jobs/9695543575#step:6:193

**Comment by AdrienLeGuillou** [comment]
I fixed the issues related to this PR but there are still 2 problems:
- `netest_par` that has not been updated to reflect the changes to `netest` in EpiModel
- `pull_env_vars` that gets flagged for assigning to the global environment

Are these two functions still used by some projects? @smjenness what do you want me to do about them for this PR and longer term?

**Comment by smjenness** [comment]
Thanks - I am removing netest_par and ignoring the NOTES related to pull_env_vars.

**Pull request merged**
